import Link from "next/link";
import Logo from "@/components/Logo";
import ThemeToggle from "@/components/ThemeToggle";

export const metadata = {
  title: "Terms of Service — Leora",
};

const LAST_UPDATED = "July 25, 2026";
const CONTACT_EMAIL = "jayandhan2003@gmail.com";

export default function TermsOfService() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)" }}>
      <div className="row between" style={{ height: 64, padding: "0 24px", borderBottom: "1px solid var(--line)" }}>
        <Link href="/" className="row" style={{ gap: 10 }}>
          <Logo /><span style={{ fontWeight: 600, letterSpacing: "-0.02em" }}>Leora</span>
        </Link>
        <ThemeToggle />
      </div>

      <div className="container" style={{ maxWidth: 720, padding: "56px 24px 80px" }}>
        <h1 className="t-h2" style={{ marginBottom: 8 }}>Terms of Service</h1>
        <p className="t-2" style={{ fontSize: "0.85rem", marginBottom: 40 }}>Last updated: {LAST_UPDATED}</p>

        <div style={{ display: "flex", flexDirection: "column", gap: 28, fontSize: "0.95rem", lineHeight: 1.7 }}>
          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>Agreement to Terms</h2>
            <p className="t-2">
              By creating an account or using Leora (the web app, mobile app, or our Telegram/WhatsApp bots),
              you agree to these terms. If you don't agree, please don't use the service.
            </p>
          </section>

          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>The Service</h2>
            <p className="t-2">
              Leora runs AI agents that monitor topics you configure and deliver voice-note briefings
              summarizing what they find, through the app and/or connected channels like Telegram and
              WhatsApp. Briefing content is generated by AI from source material we can't fully control the
              accuracy of — treat briefings as a convenient summary, not a verified source of truth.
            </p>
          </section>

          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>Your Account</h2>
            <p className="t-2">
              You're responsible for the activity that happens under your account, and for keeping access to
              your Google account (or linked Telegram/WhatsApp) secure. Let us know if you believe your
              account has been compromised.
            </p>
          </section>

          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>Acceptable Use</h2>
            <p className="t-2" style={{ marginBottom: 10 }}>You agree not to:</p>
            <ul className="t-2" style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 6 }}>
              <li>Use Leora to monitor or generate content for unlawful, harassing, or abusive purposes.</li>
              <li>Attempt to disrupt, reverse-engineer, or gain unauthorized access to the service or its infrastructure.</li>
              <li>Use the WhatsApp or Telegram integrations to send unsolicited messages to third parties.</li>
            </ul>
          </section>

          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>Your Data</h2>
            <p className="t-2">
              How we collect, use, and store your data is described in our{" "}
              <Link href="/privacy" style={{ color: "var(--accent)" }}>Privacy Policy</Link>. You can delete
              your agents and data at any time from within the app.
            </p>
          </section>

          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>Termination</h2>
            <p className="t-2">
              You may stop using Leora and delete your account at any time. We may suspend or terminate
              access if these terms are violated, or if needed to protect the service or other users.
            </p>
          </section>

          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>Disclaimer &amp; Limitation of Liability</h2>
            <p className="t-2">
              Leora is provided "as is," without warranties of any kind. We do our best to keep the service
              reliable and briefings accurate, but we're not liable for decisions made based on AI-generated
              summaries, or for service interruptions, to the fullest extent permitted by law.
            </p>
          </section>

          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>Changes to These Terms</h2>
            <p className="t-2">
              If we make material changes, we'll update the "Last updated" date above. Continued use after a
              change means you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="t-h3" style={{ marginBottom: 10 }}>Contact</h2>
            <p className="t-2">
              Questions about these terms? Reach us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "var(--accent)" }}>{CONTACT_EMAIL}</a>.
            </p>
          </section>
        </div>

        <div style={{ marginTop: 48 }}>
          <Link href="/" className="nav-link" style={{ fontSize: "0.85rem" }}>← Back to home</Link>
        </div>
      </div>
    </div>
  );
}
